CREATE TABLE MCO
(
	MCO                   VARCHAR2(10)  NOT NULL ,
	MCO_NM                VARCHAR2(10)  NULL ,
	MDE                   VARCHAR2(10)  NULL 
);



CREATE UNIQUE INDEX XPK_MCO ON MCO
(MCO  ASC);



ALTER TABLE MCO
	ADD CONSTRAINT  XPK_MCO PRIMARY KEY (MCO);



CREATE TABLE SCO
(
	SCO                   VARCHAR2(10)  NOT NULL ,
	SCO_DES               VARCHAR2(30)  NULL ,
	KY                    VARCHAR2(10)  NOT NULL ,
	MCO                   VARCHAR2(10)  NOT NULL 
);



CREATE UNIQUE INDEX XPK_SCO ON SCO
(KY  ASC);



ALTER TABLE SCO
	ADD CONSTRAINT  XPK_SCO PRIMARY KEY (KY);



CREATE UNIQUE INDEX XAK1_UK1 ON SCO
(MCO  ASC,SCO  ASC);



ALTER TABLE SCO
ADD CONSTRAINT  XAK1_UK1 UNIQUE (MCO,SCO);



CREATE TABLE EMP
(
	EMP_NO                VARCHAR2(10)  NOT NULL ,
	EMP_NM              VARCHAR2(10)  NULL ,
	REG_NO                VARCHAR2(20)  NULL ,
	HP                    VARCHAR2(10)  NULL ,
	WO_TM                 VARCHAR2(10)  NULL ,
	PO                    VARCHAR2(10)  NULL 
);



CREATE UNIQUE INDEX XPK_EMP ON EMP
(EMP_NO  ASC);



ALTER TABLE EMP
	ADD CONSTRAINT  XPK_EMP PRIMARY KEY (EMP_NO);