--테이블 생성 제약조건 부여
CREATE TABLE test_tab2(
    ID NUMBER(2),
    NAME VARCHAR2(10),
    CONSTRAINT ID_PK PRIMARY KEY (ID) );

CREATE TABLE emp_tab(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    DEPTNO VARCHAR2(6) NOT NULL,
    CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY(DEPTNO)
    REFERENCES TDEPT(DEPT_CODE)
    );

SELECT * FROM TDEPT;
DESC TDEPT;

CREATE TABLE UNI_TAB2(
    DEPTNO NUMBER(2),
    DNAME CHAR(14),
    CONSTRAINT UNI_TAB_DEPTNO_UK UNIQUE(DEPTNO)
);

CREATE TABLE NN_TAB1(
    DEPTNO NUMBER(2) NOT NULL,
    DNAME CHAR(14),
    LOC CHAR(14)
);

CREATE TABLE CK_TAB2(
    DEPTNO NUMBER,
    DNAME CHAR(14),
    LOC CHAR(13),
    CONSTRAINT UNI_TAB_DEPTNO_CK CHECK
    (DEPTNO IN(10,20,30,40,50))
);
--제약 조건 추가 삭제
ALTER TABLE UNI_TAB2
ADD CONSTRAINT UNI_TAB_DNAME_UK UNIQUE(DNAME); 

ALTER TABLE UNI_TAB2
DROP CONSTRAINT UNI_TAB_DNAME_UK;

ALTER TABLE UNI_TAB2
DISABLE CONSTRAINT UNI_TAB_DEPTNO_UK;

ALTER TABLE UNI_TAB2
ENABLE CONSTRAINT UNI_TAB_DEPTNO_UK;
--제약조건 조회
SELECT * FROM TEVAL;
--CONSTRAINT
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TEVAL';
--COLUMNS 관련
SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'TEVAL';
--
CREATE TABLE TEMP_30
    AS SELECT *
    FROM TEMP
    WHERE DEPT_CODE = 'AA0001';

SELECT * FROM TEMP_30;
--테이블 추가
ALTER TABLE TEMP_30
ADD ETC VARCHAR2(50);
--테이블 수정
ALTER TABLE TEMP_30
MODIFY EMP_NAME VARCHAR2(15);
DESC TEMP_30;
--컬럼 삭제
ALTER TABLE TEMP_30
DROP (EMP_NAME);
--테이블 삭제
DROP TABLE TEMP_30;
--모든 행 삭제
TRANCATE TABLE 테이블명;
--주석 
COMMENT ON TABLE EMP IS 'EMPLOYEE INFORMATION';
--FK가 제대로 걸렸는지 어떤 TABLE 어떤COLUMN
--1.FK = R이므로 CONSTRAINT_NAME이 R인걸 찾음
--2.FK 이름을 가지고 USER_CONS_COLUMNS FK가 걸린 COLUMNS이 나옴
--3.FK가 물고있는 이름 = 상대방의 PK
--4.PK로 2번을 수행
--(추가 설명 1.참조키 R CONSTRAINT를 찾는다 FK의 명칭
--           컬럼 : USER_CONS_COLUMNS FK가 어느 컬럼에 걸려있는지
--          2.R_CONSTRAINT_NAME을 찾는다 그 FK가 물려있는 PK를 찾는다
--          컬럼 : USER_CONS_COLUMNS PK가 어떤컬럼을 물고있는지 찾는다
-- 조인을 걸어야함 C -> R접근
SELECT * FROM USER_CONSTRAINTS
AND CONSTRAINT_TYPE = 'R';

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TDEPT'
AND CONSTRAINT_TYPE = 'P';
--1번 2번 합친거 검색
SELECT * FROM USER_CONS_COLUMNS
WHERE CONSTRAINT_NAME IN ('FK_FROM_TDEPT','SYS_C0011063');