INSERT INTO LINE (LINE_NO, LINE_NAME) VALUES ('L01','1번 제조 라인');
INSERT INTO LINE (LINE_NO, LINE_NAME) VALUES ('L02','2번 제조 라인');
INSERT INTO LINE (LINE_NO, LINE_NAME) VALUES ('L03','3번 제조 라인');

INSERT INTO SPEC (SPEC_CODE, SEPC_NAME) VALUES ('501','소방차');
INSERT INTO SPEC (SPEC_CODE, SEPC_NAME) VALUES ('502','경찰차');
INSERT INTO SPEC (SPEC_CODE, SEPC_NAME) VALUES ('503','구급차');
INSERT INTO SPEC (SPEC_CODE, SEPC_NAME) VALUES ('504','스포츠카');
INSERT INTO SPEC (SPEC_CODE, SEPC_NAME) VALUES ('505','장갑차');

ALTER TABLE ITEM ADD ( TY VARCHAR2(04));

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I01','소방차 바디','501');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I02','경찰차 바디','502');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I03','구급차 바디','503');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I04','스포츠카 바디','504');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I05','장갑차 바디','505');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I06','소형차 바퀴');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I07','중형차 바퀴');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I08','장갑차 바퀴');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I09','소방차 문짝','501');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I10','경찰차 문짝','502');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I11','구급차 문짝','503');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I12','스포츠카 문짝','504');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I13','장갑차 문짝','505');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I14','경광등');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I15','경찰차 스티커','502');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I16','소방차 스티커','501');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I17','구급차 스티커','503');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I18','장갑차 스티커','505');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I19','스포츠카 스티커','504');
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME) VALUES ('I20','포장박스');
