--17
INSERT INTO BOM (SPEC_CODE, ITEM_CODE, ITEM_QTY)
SELECT 'S'||LPAD(A.NO,2,'0') SCD,
       'I'||LPAD(B.NO,2,'0') ICD,
       CEIL(DBMS_RANDOM.VALUE(2,5))
FROM STUDY01.T1_DATA A, STUDY01.T1_DATA B
WHERE A.NO<=5
AND B.NO <= 10
AND B.NO BETWEEN A.NO AND A.NO+5;
--18
INSERT INTO INPUT_PLAN(INPUT_PLAN_DATE, LINE_NO, PLAN_SEQ, SPEC_CODE)
SELECT  TO_CHAR(TO_DATE('20191001','YYYYMMDD')+C.NO-1, 'YYYYMMDD') INDATE,
        'L'||LPAD(A.NO,2,'0') LCD, B.NO, 'S'||LPAD(MOD(A.NO*10 + B.NO,5)+1,2,'0') C1
FROM T1_DATA A,
     T1_DATA B,
     T1_DATA C
WHERE A.NO <=3
AND B.NO <= 10
AND C.NO <= 5
ORDER BY 1,2,3;
--19.
INSERT INTO JIT_DELIVERY_PLAN(DELIVERY_DATE, LINE_NO, DELIVERY_SEQ, ITEM_CODE, ITEM_QTY)
SELECT A.INPUT_PLAN_DATE, A.LINE_NO, CEIL(A.PLAN_SEQ/2), B.ITEM_CODE, SUM(B.ITEM_QTY)
FROM INPUT_PLAN A, BOM B
WHERE B.SPEC_CODE = A.SPEC_CODE
GROUP BY A.INPUT_PLAN_DATE, A.LINE_NO, CEIL(A.PLAN_SEQ/2), B.ITEM_CODE
ORDER BY 1,2,3;
--20.
SELECT INPUT_PLAN_DATE,
        LINE_NO,
        SPEC_CODE,
        COUNT(SPEC_CODE) NS
FROM INPUT_PLAN
GROUP BY INPUT_PLAN_DATE,
        LINE_NO,
        SPEC_CODE
ORDER BY 1,2,4 DESC;